# Generated by Django 3.0.10 on 2023-12-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('enderecoArquivo', models.FileField(blank=True, null=True, upload_to='')),
                ('periodoHistorico', models.CharField(max_length=100)),
                ('anoArquivo', models.IntegerField()),
                ('descricao', models.TextField()),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=15)),
                ('dataNascimento', models.DateField()),
                ('senha', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cadastro',
            },
        ),
    ]
