# Generated by Django 3.0.10 on 2024-02-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=15)),
                ('dataNascimento', models.DateField()),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('cnpj', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('ramo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'fornecedor',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.BigIntegerField()),
                ('sexo', models.CharField(max_length=15)),
                ('dataNascimento', models.DateField()),
                ('senha', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='loteProd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quanti', models.IntegerField()),
                ('fabri', models.DateField()),
                ('vali', models.DateField()),
                ('idPRoduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Produto')),
            ],
            options={
                'db_table': 'loteProd',
            },
        ),
        migrations.CreateModel(
            name='comprarProduto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantProd', models.IntegerField()),
                ('cpfCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Cliente')),
                ('idPrduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Produto')),
            ],
            options={
                'db_table': 'clienteProd',
            },
        ),
    ]
