# Generated by Django 3.0.10 on 2024-02-18 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprarprod',
            old_name='idPrduto',
            new_name='idProduto',
        ),
    ]
